### ISSUE TITLE
Misunderstanding <<:

### ISSUE THREAD

**Issue by axlroden** [longkai/kubernetes-yaml-formatter#18]
I have this code:

    restic:
      <<: *image

When I save with this extension enabled it does this:

    restic:
      !!merge <<: *image

is there a way to disable this ?

**Comment by kiliantyler** [comment]
I've taken it upon myself to improve this extension since it hasn't had an update in quite a while.
The feature that you're requesting is available in the base `yamlfmt` and added as an option here:
https://github.com/kiliantyler/kubernetes-yaml-formatter-x?tab=readme-ov-file#extension-settings

`kubernetes-yaml-formatter-x.dropMergeTags`

**Comment by axlroden** [comment]
thankyou! Works like a treat.

**Comment by longkai** [comment]
The v2 version has been released on VSCode and fix this issue.

Give it a try!
