### ISSUE TITLE
Prevent inlineScript from formatting to a single line

### ISSUE THREAD

**Issue by b-rand** [longkai/kubernetes-yaml-formatter#5]
When I am writing a multi-line inline script, the formatter will automatically take all of the lines and put them on one line with characters like \n to separate new lines. This makes editing the code later much more difficult to do. Is it possible to turn this feature off?

**Here is an example**
Before Formatting
```bash
        inlineScript: |
          scope=$(az resource show -g ${{ parameters.resourceGroup }} -n ${{ parameters.clusterName }} --resource-type "Microsoft.ContainerService/managedClusters" --query id -o tsv) 
          az role assignment create --role "b1ff04bb-8a4e-4dc4-8eb5-8693973ce19b" --assignee-object-id $(servicePrincipalId) --assignee-principal-type ServicePrincipal --scope $scope

```
After Formatting
```bash
        inlineScript: "scope=$(az resource show -g ${{ parameters.resourceGroup }} -n ${{ parameters.clusterName }} --resource-type \"Microsoft.ContainerService/managedClusters\" --query id -o tsv) \naz role assignment create --role \"b1ff04bb-8a4e-4dc4-8eb5-8693973ce19b\" --assignee-object-id $(servicePrincipalId) --assignee-principal-type ServicePrincipal --scope $scope\n"
```

**Comment by longkai** [comment]
Hello, actually, this is the underlying go yaml lib does.

I look into the source code, the rule multi-line literal formatted to a single line are:

1. ends with a space
2. a space with a new line
3. contains special chars(e.g., unprintable)

I suppose it does it intentionally for unintentional escape chars since unprintable chars hard to find.

In you case, the first line end with `--query id -o tsv) `. It hit the rule 2.

**Comment by b-rand** [comment]
Thank you!

**Comment by pie-r** [comment]
For other having the same issue, I "solved" it using the "|"
```
 description: |
              'xxxxxx'

```

**Comment by rcdailey** [comment]
I think this should be reopened. Line continuation using `>` shouldn't be reformatted.
