### ISSUE TITLE
Question: how to apply it to helm-template files?

### ISSUE THREAD

**Issue by RafalSkolasinski** [longkai/kubernetes-yaml-formatter#8]
This is great, finally sane indent for list in Kubernetes / Ansible yaml files. 
Just a question - how can I make it also work if file is recognized as `helm-template`? 

I tried to set 
```
    "[helm-template]": {
        "editor.defaultFormatter": "kennylong.kubernetes-yaml-formatter"
    },
```
but VS Code still complains that "There is no formatter for 'helm' files installed.".

**Comment by longkai** [comment]
Hi!

Sorry for the delay.

I use helm very often. But since helm is not really yaml but a template-engine we cannot format the mixed two directly.

However, for the template part you can use builtin function like `indentn`.

for the yaml part, the new v2 version has implemented a range format, so just select range code and the extension will format those region.

**Comment by longkai** [comment]
You can config with(which is the default value):

```json
"[helm]": {
  "editor.defaultFormatter": "kennylong.kubernetes-yaml-formatter",
  "editor.formatOnSave": false
},
"[ansible]": {
  "editor.defaultFormatter": "kennylong.kubernetes-yaml-formatter",
  "editor.formatOnSave": false
}
```
