### ISSUE TITLE
Format on save does not work with "editor.formatOnSaveMode": "modifications"

### ISSUE THREAD

**Issue by pre** [longkai/kubernetes-yaml-formatter#9]
Format works when selecting `>Format document`.

However, with `"editor.formatOnSaveMode": "modifications"` in global user settings format on save does not work. 
Format on save does work 
* without `editor.formatOnSaveMode` being set 
* with `"editor.formatOnSaveMode": "file"`

Project .vscode/settings:

```json
  "[yaml]": {
    "editor.defaultFormatter": "kennylong.kubernetes-yaml-formatter",
    "editor.formatOnSave": true
  },
  "files.associations": {
    "*.yml": "yaml",
    "*.yaml": "yaml"
  },
```

**Comment by longkai** [comment]
Hi! Thanks for reaching out.

The `editor.formatOnSaveMode` works because the default value `file` formats the entire file every time you save it.

On the other hand, the `modifications` formats only the lines that have been modified since the last save(requires vcs like git). It’s useful in reducing the amount of change applied during formatting in collaborative settings or when you’re concerned about large files.

**Comment by pre** [comment]
Yes! And at the time of writing, the latter setting did not work.
